backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Activities"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Početna"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Top, name: top, widget: string, required: false}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: text}
              - {label: "Height (rem)", name: height, widget: number, value_type: "int", min: 10, max: 100, step: 1, required: false}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Page, name: page, widget: string, required: false}
          - label: Story
            name: story
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Cards
                name: cards
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Text, name: text, widget: text}
          - label: Poster
            name: poster
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - label: Colors
                name: colors
                widget: list
                fields: 
                  - {label: Code, name: code, widget: text}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Page, name: page, widget: string}
          - label: Membership
            name: membership
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: text}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Page, name: page, widget: string}
      - file: "src/pages/about/index.md"
        label: "O društvu"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Top, name: top, widget: string, required: false}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: text}
              - {label: "Height (rem)", name: height, widget: number, value_type: "int", min: 10, max: 100, step: 1, required: false}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Page, name: page, widget: string, required: false}
          - label: "Left Text"
            name: leftText
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Body, name: body, widget: text}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Page, name: page, widget: string}
              - {label: "Big", name: isBig, widget: boolean}
          - label: Story
            name: story
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Cards
                name: cards
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Text, name: text, widget: text}
          - label: "Text With Image"
            name: textWithImage
            widget: object
            fields:
              - {label: Body, name: body, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Membership
            name: membership
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: text}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Page, name: page, widget: string}
      - file: "src/pages/membership/index.md"
        label: "Članstvo"
        name: "membership"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "membership-page"}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Top, name: top, widget: string, required: false}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: text}
              - {label: "Height (rem)", name: height, widget: number, value_type: "int", min: 10, max: 100, step: 1, required: false}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Page, name: page, widget: string, required: false}
          - label: Pricing
            name: pricing
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Plans
                name: plans
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Value, name: value, widget: string}
                  - {label: Description, name: description, widget: string}
                  - {label: "Big Value", name: isValueBig, widget: boolean}
          - label: "Left Text"
            name: leftText
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Body, name: body, widget: text}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Page, name: page, widget: string}
              - {label: "Big", name: isBig, widget: boolean}
          - label: Payment
            name: payment
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: Details
                name: details
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Value, name: value, widget: string}
                  - {label: Number, name: isNumber, widget: boolean}
      - file: "src/pages/membership/application.md"
        label: "Nova prijava"
        name: "membershipApplication"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "membership-application-page"}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Top, name: top, widget: string, required: false}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: text}
              - {label: "Height (rem)", name: height, widget: number, value_type: "int", min: 10, max: 100, step: 1, required: false}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Page, name: page, widget: string, required: false}
          - label: Form
            name: form
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - label: Sections
                name: sections
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - label: Fields
                    name: fields
                    widget: list
                    fields:
                      - {label: Title, name: title, widget: string}
                      - {label: Name, name: name, widget: string}
                      - {label: Type, name: type, widget: select, options: ["checkbox", "date", "email", "file", "hidden", "image", "number", "password", "radio", "tel", "text", "textarea", "time", "url"]}
                      - {label: Required, name: isRequired, widget: boolean, required: false}
                      - {label: "Full Width", name: isFullWidth, widget: boolean, required: false}
              - {label: Button, name: button, widget: string}
              - {label: PDF, name: isPdf, widget: boolean}
              - label: "PDF Document Details"
                name: pdf
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - label: Header
                    name: header
                    widget: object
                    fields:
                      - {label: Title, name: title, widget: string}
                      - label: "Left Column Item"
                        name: leftColumn
                        widget: list
                        fields:
                          - {label: Text, name: text, widget: string}
                      - label: "Right Column Item"
                        name: rightColumn
                        widget: list
                        fields:
                          - {label: Text, name: text, widget: string}
                  - {label: Day, name: day, widget: string}
                  - {label: Signature, name: signature, widget: string}
                  - {label: "Default Full Name", name: defaultFullName, widget: string}
                  - label: "Payment Details"
                    name: paymentDetails
                    widget: list
                    fields:
                      - {label: Text, name: text, widget: string}
                  - label: "Mailing Details"
                    name: mailingDetails
                    widget: list
                    fields:
                      - {label: Text, name: text, widget: string}
              - label: Success
                name: success
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Subtitle, name: subtitle, widget: string}
                  - {label: Button, name: button, widget: string}         
      - file: "src/pages/contact/index.md"
        label: "Kontakt"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "membership-application-page"}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Top, name: top, widget: string, required: false}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: text}
              - {label: "Height (rem)", name: height, widget: number, value_type: "int", min: 10, max: 100, step: 1, required: false}
              - label: Link
                name: link
                widget: object
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Page, name: page, widget: string, required: false}
          - label: Form
            name: form
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - label: Sections
                name: sections
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - label: Fields
                    name: fields
                    widget: list
                    fields:
                      - {label: Title, name: title, widget: string}
                      - {label: Name, name: name, widget: string}
                      - {label: Type, name: type, widget: select, options: ["checkbox", "date", "email", "file", "hidden", "image", "number", "password", "radio", "tel", "text", "textarea", "time", "url"]}
                      - {label: Required, name: isRequired, widget: boolean, required: false}
                      - {label: "Full Width", name: isFullWidth, widget: boolean, required: false}
              - {label: Button, name: button, widget: string}
              - {label: PDF, name: isPdf, widget: boolean}
              - label: Success
                name: success
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Subtitle, name: subtitle, widget: string}
                  - {label: Button, name: button, widget: string}

                          